React code
salvik21/RenomaReact pull request #1
Opened 2022-09-15 16:42 UTC by salvik21

My first react code, by lovely to my)

2022-09-26 09:43 UTC, YuraLeo94 requested changes
**Reminder: code style is one of the important things.** 
Use format code for all jsx files.

Also, please add me and Nikolai as reviewers.

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Paragraph/ParagraphAtom.jsx
> +function ParagraphAtom(props) {
Not necessarily this component, since you just wrap `p` tag. Use instead this component just `<p>`

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/LogoAtom/LogoAtom.jsx
> +function LogoAtom(props) {
Don't need postfix Atom, just Logo

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Subtile/SubtitleAtom.jsx
> +function SubtitleAtom(props) {
Not necessarily this component, since you just wrap `h3` tag. Use instead this component just `<h3>`

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Titles/TitleAtom.jsx
> +function TitleAtom(props) {
Not necessarily this component, since you just wrap `h1` tag. Use instead this component just `<h1>`

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Icon/IconAtom.jsx
> +function Icon(props) {
this component is not needed, use the tag directly.

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Image/ImageAtom.jsx
> +function ImageAtom(props) {
this component is not needed, use the tag directly.

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Label/LabelAtom.jsx
> +function LabelAtom(props) {
this component is not needed, use the tag directly.

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Atoms/Link/LinkAtom.jsx
> +function LinkAtom(props) {
this component is not needed, use the tag directly.

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Molecules/Button/ForwardButton/ForwardButton.jsx
> +function ForwardButton() {
this is atom component

2022-09-26 09:43 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselImage/CarouselImage.jsx
> +function CaruselImages() {
this is atom component

2022-09-30 09:57 UTC, YuraLeo94 requested changes

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Atoms/CartIcon/CartIcon.jsx
> +            <img src={CartImage} alt="Cart Image" onClick={onClick} />
Please add a className cart-icon for the image instead of its wrapper.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Atoms/CloseIcon/CloseIcon.jsx
> +            <img src={CloseImage} alt="Close Image" onClick={onClick} />
Same you give a name for the wrapper instead of your icon.
```
<div className="close-icon"> - **close-icon-wrapper**
            <img src={CloseImage} alt="Close Image" onClick={onClick} /> - **close-icon**
</div>
```

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Atoms/HamburgerIcon/HamburgerIcon.jsx
> +            <img src={HamburgerImage} alt="Hamburger Image" onClick={onClick} />
Same issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/AboutContext/AboutContext.jsx
> +        </div>
Same class issue as in comments above. If you can't apply style for a component then need to send it as a props.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/AboutImages/AboutImages.jsx
> +        </div>
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/Button/BackButton/BackButton.jsx
> +        <div className="button">
it is forward-button, please add more clear name

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/Button/BackButton/BackButton.jsx
> +            <Image src= {ForwardImage} alt="Imageone"/>
If the below styles do not work for `div`, then please add it for the image itself. `forward-icon` or `forward-image`
```
.button > img {
    transform: rotate(180deg);
    width: 35px;
    height: 35px;
}
```

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/Button/ForwardButton/ForwardButton.jsx
> +        <div className="forward-button">
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselImage/CarouselImage.jsx
> +        </div>
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselTitles/CarouselTitles.jsx
> +            <   Subtitle  subTitle="for you" />
What about code styling?!

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselTitles/CarouselTitles.jsx
> +            <div className="subtitle-carousel">
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/GalleryImages/GalleryImages.jsx
> +        <ul className="gallery-img-wrapper">
rename please for `gallery-img-container`

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/GalleryImages/GalleryImages.jsx
> +        {ImgElement.map((item) => <li className="gallery-img">
`<li>` is wrapper of img

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/Icons/Icons.jsx
> +function Icons () {
please rename to the `HeaderNavBar`, also after it update className

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Molecules/SocialNetworksIcons/SocialNetworksIcons.css
> +.social-networks-icons > a > img {
okay, I see no reason to create thousands of `[className] > tag > tag > etc.`, give the class name to the image

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Organisms/Carousel/Carousel.jsx
> +            <div className="carousel-button">
do you have one button in this `div`?

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Organisms/Footer/Footer.jsx
> +            </div>
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Organisms/Gallery/Gallery.jsx
> +            </div>
Same class issue as in comments above.

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Organisms/Nav/Nav.jsx
> +                <Renoma />
is it a logo?

2022-09-30 09:57 UTC, YuraLeo94 commented on src/componets/Organisms/Nav/Nav.css
> +.nav > h1 {
give class name for the logo itself

2022-09-30 09:57 UTC, YuraLeo94 commented on src/font/Montserrat-Regular.css
> +@font-face {
create `font.css` file for all fonts

2022-09-30 10:02 UTC, YuraLeo94 commented on src/componets/Molecules/Button/BackButton/BackButton.jsx
> +function BackButton() {
@salvik21

2022-09-30 10:07 UTC, YuraLeo94 commented on src/componets/Molecules/Button/BackButton/BackButton.jsx
> +        <div className="button">
Move button to the atoms
<img width="146" alt="image" src="https://user-images.githubusercontent.com/71021726/193247308-b7d20245-4fec-46c8-9658-63f044c1e9d7.png">

2022-10-03 13:01 UTC, YuraLeo94 commented on src/componets/Atoms/CloseIcon/CloseIcon.jsx
> +function CloseIcon({ onClick }) {
Use ImageAtom to show close image

2022-10-03 13:02 UTC, YuraLeo94 commented on src/componets/Atoms/CartIcon/CartIcon.jsx
> +function CartIcon({ onClick }) {
Use ImageAtom to show cart image

2022-10-03 13:06 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselImage/CarouselImage.css
> +.carusel-img {
Stick to one approach naming `...-image-...` or `...-img-...`

2022-10-03 13:08 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselImage/CarouselImage.jsx
> +function CaruselImages() {
Do you move this component to the atom? @salvik21

2022-10-03 13:08 UTC, YuraLeo94 commented on src/componets/Molecules/CarouselTitles/CarouselTitles.css
> +.titls-carousel-wrapper {
typo

2022-10-03 13:10 UTC, YuraLeo94 commented on src/componets/Molecules/GalleryImages/GalleryImages.css
> +    object-fit: cover;
Stick to one approach naming `...-image-...` or `...-img-...`

2022-10-03 13:13 UTC, YuraLeo94 commented on src/componets/Molecules/NavPanel/NavPanel.jsx
> +function Icons() {
Not clear naming

2022-10-07 14:43 UTC, YuraLeo94 requested changes

2022-10-07 14:43 UTC, YuraLeo94 commented on src/componets/Atoms/Image/ImageAtom.jsx
> +        <img className={imageClass} src={src} alt={alt} onClick={onClick} />
If I remember correctly, right now you only have to make the visual part of the application.
So my question is, what is it `onClick={onClick}`? How does this help visualize your components right now?

2022-10-07 15:03 UTC, salvik21 commented on src/componets/Atoms/Image/ImageAtom.jsx
> +        <img className={imageClass} src={src} alt={alt} onClick={onClick} />
I'm sorry I forgot to delete I was in a hurry to finish

2022-10-07 15:16 UTC, YuraLeo94 commented on src/componets/Atoms/Image/ImageAtom.jsx
>  function ImageAtom({ src, alt, imageClass, onClick }) {
`onClick` remove please

2022-10-07 15:20 UTC, YuraLeo94 approved these changes

2022-10-07 15:53 UTC, salvik21 commented on src/componets/Molecules/CarouselTitles/CarouselTitles.css
> +.titls-carousel-wrapper {
corrected

2022-10-09 17:31 UTC, CoobQ approved these changes

2022-10-09 17:33 UTC, merged