added cart menu view
salvik21/RenomaReact pull request #2
Opened 2022-10-10 16:30 UTC by salvik21

2022-10-11 21:32 UTC, YuraLeo94 requested changes

2022-10-11 21:32 UTC, YuraLeo94 commented on src/componets/Molecules/CartMenu/CartMenu.jsx
> +                    {item.atvButton ? LabelElm(item.text) : LinkElm(item.href, item.text)}
What reason need to use `LabelElm` and `LinkElm`? Why you can't use plain component?

2022-10-11 21:32 UTC, YuraLeo94 commented on src/componets/Molecules/NavPanel/NavPanel.jsx
> +        <div className="nanavigation-wrapper">
First questions what is it `nana..-wrapper`?
Second questions where you use it?

2022-10-11 22:58 UTC, salvik21 commented on src/componets/Molecules/CartMenu/CartMenu.jsx
> +                    {item.atvButton ? LabelElm(item.text) : LinkElm(item.href, item.text)}
did not work at the very beginning of the attempts

2022-10-12 08:37 UTC, YuraLeo94 approved these changes

2022-10-12 10:18 UTC, merged